// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/flashlink/v1/flashlink.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	LongUrl       string                 `protobuf:"bytes,3,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	Domain        string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	Status        uint32                 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortLink) Reset() {
	*x = ShortLink{}
	mi := &file_proto_flashlink_v1_flashlink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortLink) ProtoMessage() {}

func (x *ShortLink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flashlink_v1_flashlink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortLink.ProtoReflect.Descriptor instead.
func (*ShortLink) Descriptor() ([]byte, []int) {
	return file_proto_flashlink_v1_flashlink_proto_rawDescGZIP(), []int{0}
}

func (x *ShortLink) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShortLink) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ShortLink) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *ShortLink) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ShortLink) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

func (x *ShortLink) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ShortLink) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ShortLink) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateShortLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongUrl       string                 `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkRequest) Reset() {
	*x = CreateShortLinkRequest{}
	mi := &file_proto_flashlink_v1_flashlink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkRequest) ProtoMessage() {}

func (x *CreateShortLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flashlink_v1_flashlink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateShortLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_flashlink_v1_flashlink_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortLinkRequest) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *CreateShortLinkRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CreateShortLinkRequest) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

type CreateShortLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	LongUrl       string                 `protobuf:"bytes,3,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkResponse) Reset() {
	*x = CreateShortLinkResponse{}
	mi := &file_proto_flashlink_v1_flashlink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkResponse) ProtoMessage() {}

func (x *CreateShortLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flashlink_v1_flashlink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateShortLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_flashlink_v1_flashlink_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShortLinkResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateShortLinkResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *CreateShortLinkResponse) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *CreateShortLinkResponse) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

type ResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_proto_flashlink_v1_flashlink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flashlink_v1_flashlink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_proto_flashlink_v1_flashlink_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ShortLink             `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_proto_flashlink_v1_flashlink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flashlink_v1_flashlink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_proto_flashlink_v1_flashlink_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveResponse) GetItem() *ShortLink {
	if x != nil {
		return x.Item
	}
	return nil
}

type LinkStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkStatsRequest) Reset() {
	*x = LinkStatsRequest{}
	mi := &file_proto_flashlink_v1_flashlink_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkStatsRequest) ProtoMessage() {}

func (x *LinkStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flashlink_v1_flashlink_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkStatsRequest.ProtoReflect.Descriptor instead.
func (*LinkStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_flashlink_v1_flashlink_proto_rawDescGZIP(), []int{5}
}

func (x *LinkStatsRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type LinkStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Pv            uint64                 `protobuf:"varint,2,opt,name=pv,proto3" json:"pv,omitempty"`
	Uv            uint64                 `protobuf:"varint,3,opt,name=uv,proto3" json:"uv,omitempty"`
	TodayPv       uint64                 `protobuf:"varint,4,opt,name=today_pv,json=todayPv,proto3" json:"today_pv,omitempty"`
	Referers      []*RefererStat         `protobuf:"bytes,5,rep,name=referers,proto3" json:"referers,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkStatsResponse) Reset() {
	*x = LinkStatsResponse{}
	mi := &file_proto_flashlink_v1_flashlink_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkStatsResponse) ProtoMessage() {}

func (x *LinkStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flashlink_v1_flashlink_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkStatsResponse.ProtoReflect.Descriptor instead.
func (*LinkStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_flashlink_v1_flashlink_proto_rawDescGZIP(), []int{6}
}

func (x *LinkStatsResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LinkStatsResponse) GetPv() uint64 {
	if x != nil {
		return x.Pv
	}
	return 0
}

func (x *LinkStatsResponse) GetUv() uint64 {
	if x != nil {
		return x.Uv
	}
	return 0
}

func (x *LinkStatsResponse) GetTodayPv() uint64 {
	if x != nil {
		return x.TodayPv
	}
	return 0
}

func (x *LinkStatsResponse) GetReferers() []*RefererStat {
	if x != nil {
		return x.Referers
	}
	return nil
}

func (x *LinkStatsResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RefererStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Referer       string                 `protobuf:"bytes,1,opt,name=referer,proto3" json:"referer,omitempty"`
	Pv            uint64                 `protobuf:"varint,2,opt,name=pv,proto3" json:"pv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefererStat) Reset() {
	*x = RefererStat{}
	mi := &file_proto_flashlink_v1_flashlink_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefererStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefererStat) ProtoMessage() {}

func (x *RefererStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flashlink_v1_flashlink_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefererStat.ProtoReflect.Descriptor instead.
func (*RefererStat) Descriptor() ([]byte, []int) {
	return file_proto_flashlink_v1_flashlink_proto_rawDescGZIP(), []int{7}
}

func (x *RefererStat) GetReferer() string {
	if x != nil {
		return x.Referer
	}
	return ""
}

func (x *RefererStat) GetPv() uint64 {
	if x != nil {
		return x.Pv
	}
	return 0
}

type RecordVisitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Referer       string                 `protobuf:"bytes,4,opt,name=referer,proto3" json:"referer,omitempty"`
	VisitedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=visited_at,json=visitedAt,proto3" json:"visited_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordVisitRequest) Reset() {
	*x = RecordVisitRequest{}
	mi := &file_proto_flashlink_v1_flashlink_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordVisitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordVisitRequest) ProtoMessage() {}

func (x *RecordVisitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flashlink_v1_flashlink_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordVisitRequest.ProtoReflect.Descriptor instead.
func (*RecordVisitRequest) Descriptor() ([]byte, []int) {
	return file_proto_flashlink_v1_flashlink_proto_rawDescGZIP(), []int{8}
}

func (x *RecordVisitRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RecordVisitRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RecordVisitRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *RecordVisitRequest) GetReferer() string {
	if x != nil {
		return x.Referer
	}
	return ""
}

func (x *RecordVisitRequest) GetVisitedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VisitedAt
	}
	return nil
}

type RecordVisitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordVisitResponse) Reset() {
	*x = RecordVisitResponse{}
	mi := &file_proto_flashlink_v1_flashlink_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordVisitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordVisitResponse) ProtoMessage() {}

func (x *RecordVisitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flashlink_v1_flashlink_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordVisitResponse.ProtoReflect.Descriptor instead.
func (*RecordVisitResponse) Descriptor() ([]byte, []int) {
	return file_proto_flashlink_v1_flashlink_proto_rawDescGZIP(), []int{9}
}

var File_proto_flashlink_v1_flashlink_proto protoreflect.FileDescriptor

const file_proto_flashlink_v1_flashlink_proto_rawDesc = "" +
	"\n" +
	"\"proto/flashlink/v1/flashlink.proto\x12\fflashlink.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x02\n" +
	"\tShortLink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x19\n" +
	"\blong_url\x18\x03 \x01(\tR\alongUrl\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x127\n" +
	"\texpire_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\rR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x84\x01\n" +
	"\x16CreateShortLinkRequest\x12\x19\n" +
	"\blong_url\x18\x01 \x01(\tR\alongUrl\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x127\n" +
	"\texpire_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\"\x9e\x01\n" +
	"\x17CreateShortLinkResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\x12\x19\n" +
	"\blong_url\x18\x03 \x01(\tR\alongUrl\x127\n" +
	"\texpire_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\"$\n" +
	"\x0eResolveRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\">\n" +
	"\x0fResolveResponse\x12+\n" +
	"\x04item\x18\x01 \x01(\v2\x17.flashlink.v1.ShortLinkR\x04item\"&\n" +
	"\x10LinkStatsRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\xd4\x01\n" +
	"\x11LinkStatsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x0e\n" +
	"\x02pv\x18\x02 \x01(\x04R\x02pv\x12\x0e\n" +
	"\x02uv\x18\x03 \x01(\x04R\x02uv\x12\x19\n" +
	"\btoday_pv\x18\x04 \x01(\x04R\atodayPv\x125\n" +
	"\breferers\x18\x05 \x03(\v2\x19.flashlink.v1.RefererStatR\breferers\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"7\n" +
	"\vRefererStat\x12\x18\n" +
	"\areferer\x18\x01 \x01(\tR\areferer\x12\x0e\n" +
	"\x02pv\x18\x02 \x01(\x04R\x02pv\"\xac\x01\n" +
	"\x12RecordVisitRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x12\x18\n" +
	"\areferer\x18\x04 \x01(\tR\areferer\x129\n" +
	"\n" +
	"visited_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tvisitedAt\"\x15\n" +
	"\x13RecordVisitResponse2m\n" +
	"\vLinkService\x12^\n" +
	"\x0fCreateShortLink\x12$.flashlink.v1.CreateShortLinkRequest\x1a%.flashlink.v1.CreateShortLinkResponse2Y\n" +
	"\x0fRedirectService\x12F\n" +
	"\aResolve\x12\x1c.flashlink.v1.ResolveRequest\x1a\x1d.flashlink.v1.ResolveResponse2\xb2\x01\n" +
	"\vStatService\x12O\n" +
	"\fGetLinkStats\x12\x1e.flashlink.v1.LinkStatsRequest\x1a\x1f.flashlink.v1.LinkStatsResponse\x12R\n" +
	"\vRecordVisit\x12 .flashlink.v1.RecordVisitRequest\x1a!.flashlink.v1.RecordVisitResponseB;Z9github.com/jd/flashlink/internal/interfaces/grpcapi/pb;pbb\x06proto3"

var (
	file_proto_flashlink_v1_flashlink_proto_rawDescOnce sync.Once
	file_proto_flashlink_v1_flashlink_proto_rawDescData []byte
)

func file_proto_flashlink_v1_flashlink_proto_rawDescGZIP() []byte {
	file_proto_flashlink_v1_flashlink_proto_rawDescOnce.Do(func() {
		file_proto_flashlink_v1_flashlink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_flashlink_v1_flashlink_proto_rawDesc), len(file_proto_flashlink_v1_flashlink_proto_rawDesc)))
	})
	return file_proto_flashlink_v1_flashlink_proto_rawDescData
}

var file_proto_flashlink_v1_flashlink_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_flashlink_v1_flashlink_proto_goTypes = []any{
	(*ShortLink)(nil),               // 0: flashlink.v1.ShortLink
	(*CreateShortLinkRequest)(nil),  // 1: flashlink.v1.CreateShortLinkRequest
	(*CreateShortLinkResponse)(nil), // 2: flashlink.v1.CreateShortLinkResponse
	(*ResolveRequest)(nil),          // 3: flashlink.v1.ResolveRequest
	(*ResolveResponse)(nil),         // 4: flashlink.v1.ResolveResponse
	(*LinkStatsRequest)(nil),        // 5: flashlink.v1.LinkStatsRequest
	(*LinkStatsResponse)(nil),       // 6: flashlink.v1.LinkStatsResponse
	(*RefererStat)(nil),             // 7: flashlink.v1.RefererStat
	(*RecordVisitRequest)(nil),      // 8: flashlink.v1.RecordVisitRequest
	(*RecordVisitResponse)(nil),     // 9: flashlink.v1.RecordVisitResponse
	(*timestamppb.Timestamp)(nil),   // 10: google.protobuf.Timestamp
}
var file_proto_flashlink_v1_flashlink_proto_depIdxs = []int32{
	10, // 0: flashlink.v1.ShortLink.expire_at:type_name -> google.protobuf.Timestamp
	10, // 1: flashlink.v1.ShortLink.created_at:type_name -> google.protobuf.Timestamp
	10, // 2: flashlink.v1.ShortLink.updated_at:type_name -> google.protobuf.Timestamp
	10, // 3: flashlink.v1.CreateShortLinkRequest.expire_at:type_name -> google.protobuf.Timestamp
	10, // 4: flashlink.v1.CreateShortLinkResponse.expire_at:type_name -> google.protobuf.Timestamp
	0,  // 5: flashlink.v1.ResolveResponse.item:type_name -> flashlink.v1.ShortLink
	7,  // 6: flashlink.v1.LinkStatsResponse.referers:type_name -> flashlink.v1.RefererStat
	10, // 7: flashlink.v1.LinkStatsResponse.updated_at:type_name -> google.protobuf.Timestamp
	10, // 8: flashlink.v1.RecordVisitRequest.visited_at:type_name -> google.protobuf.Timestamp
	1,  // 9: flashlink.v1.LinkService.CreateShortLink:input_type -> flashlink.v1.CreateShortLinkRequest
	3,  // 10: flashlink.v1.RedirectService.Resolve:input_type -> flashlink.v1.ResolveRequest
	5,  // 11: flashlink.v1.StatService.GetLinkStats:input_type -> flashlink.v1.LinkStatsRequest
	8,  // 12: flashlink.v1.StatService.RecordVisit:input_type -> flashlink.v1.RecordVisitRequest
	2,  // 13: flashlink.v1.LinkService.CreateShortLink:output_type -> flashlink.v1.CreateShortLinkResponse
	4,  // 14: flashlink.v1.RedirectService.Resolve:output_type -> flashlink.v1.ResolveResponse
	6,  // 15: flashlink.v1.StatService.GetLinkStats:output_type -> flashlink.v1.LinkStatsResponse
	9,  // 16: flashlink.v1.StatService.RecordVisit:output_type -> flashlink.v1.RecordVisitResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_flashlink_v1_flashlink_proto_init() }
func file_proto_flashlink_v1_flashlink_proto_init() {
	if File_proto_flashlink_v1_flashlink_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_flashlink_v1_flashlink_proto_rawDesc), len(file_proto_flashlink_v1_flashlink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_flashlink_v1_flashlink_proto_goTypes,
		DependencyIndexes: file_proto_flashlink_v1_flashlink_proto_depIdxs,
		MessageInfos:      file_proto_flashlink_v1_flashlink_proto_msgTypes,
	}.Build()
	File_proto_flashlink_v1_flashlink_proto = out.File
	file_proto_flashlink_v1_flashlink_proto_goTypes = nil
	file_proto_flashlink_v1_flashlink_proto_depIdxs = nil
}
